# runtime: python312
# service: default               # or: timesheet
# entrypoint: gunicorn -b :$PORT app:app

# env_variables:
#   SECRET_KEY: "change-me"
#   DB_HOST: "10.19.64.3"
#   DB_PORT: "3306"
#   DB_NAME: "timesheet"
#   DB_USER: "appsadmin"
#   DB_PASS: "appsadmin2025"

#   SMTP_SERVER: "smtp.datasolve-analytics.com"
#   SMTP_PORT: "587"
#   SMTP_USER: "apps.admin@datasolve-analytics.com"
#   SMTP_PASS: "datasolve@2025"

# # (optional) a little headroom
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 0
#   max_instances: 2

# # (optional) request timeouts (seconds)
# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: auto



runtime: python312
service: default
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # Flask Secret Key
  SECRET_KEY: "change-me"

  # Database Credentials
  DB_HOST: "10.19.64.3"          # <-- your SQL PRIVATE IP here
  DB_PORT: "3306"
  DB_NAME: "timesheet"
  DB_USER: "appsadmin"
  DB_PASS: "appsadmin2025"

  # SMTP Mail Credentials
  SMTP_SERVER: "smtp.datasolve-analytics.com"
  SMTP_PORT: "587"
  SMTP_USER: "apps.admin@datasolve-analytics.com"
  SMTP_PASS: "datasolve@2025"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

vpc_access_connector:
  name: "projects/theta-messenger-459613-p7/locations/asia-south1/connectors/cpp"
  egress_setting: "private-ranges-only"
