
runtime: python312
env: standard
service: logsy
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # Flask Secret Key
  SECRET_KEY: "change-me"

  # Database Credentials
  DB_HOST: "10.19.64.3"          # Cloud SQL private IP
  DB_PORT: "3306"
  DB_NAME: "timesheet"
  DB_USER: "appsadmin"
  DB_PASS: "appsadmin2025"

  # SMTP Mail Credentials
  SMTP_SERVER: "smtp.datasolve-analytics.com"
  SMTP_PORT: "587"
  SMTP_USER: "apps.admin@datasolve-analytics.com"
  SMTP_PASS: "datasolve@2025"

automatic_scaling:
  min_instances: 0          # no instance when idle → save cost
  max_instances: 1          # never more than 1 instance
  min_idle_instances: 0     # don't keep idle instances
  max_idle_instances: 0
  target_cpu_utilization: 0.65
  max_pending_latency: 2000ms

handlers:
  # Serve static files from /static/*
  - url: /static/(.*)
    static_files: static/\1
    upload: static/.*

  # All other routes handled by Flask app
  - url: /.*
    script: auto